name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "harshgoutam04@gmail.com"
          git config --global user.name "github-actions"

          git remote add hf https://harsh041503:$HF_TOKEN@huggingface.co/spaces/harsh041503/CHATBOT_APP

          git pull hf main --rebase || true

          git push hf main
